# Generated by Django 6.0.7 on 2026-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_creator',
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('creator', 'Creator')], default='free', help_text='Paid tier. Quotas come from settings.PLAN_LIMITS.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the paid plan lapses (blank = never). Past dates behave as free.', null=True),
        ),
    ]
