# Generated by Django 6.0.7 on 2026-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_creator_user_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='limit_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
