# Generated by Django 6.0.7 on 2026-07-30 03:50

import trivia.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_limit_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', validators=[trivia.validators.validate_image]),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_logo_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='brand_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
