# Generated by Django 6.0.7 on 2026-07-26 17:46

import django.db.models.deletion
import games.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trivia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trivia.category')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='BoardCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('hidden', 'Hidden'), ('open', 'Open'), ('answered', 'Answered')], default='hidden', max_length=10)),
                ('answered_correctly', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trivia.question')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='games.boardcolumn')),
            ],
            options={
                'ordering': ('column__position', 'row'),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=games.models.generate_game_code, max_length=8, unique=True)),
                ('mode', models.CharField(choices=[('drinks', 'Drinks'), ('points', 'Points')], default='drinks', max_length=10)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('finished', 'Finished')], default='lobby', max_length=10)),
                ('questions_per_category', models.PositiveSmallIntegerField(default=5)),
                ('buzzer_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.boardcell')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='games.game'),
        ),
        migrations.AddField(
            model_name='boardcell',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='games.game'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('host', 'Host'), ('player', 'Player/Team buzzer')], default='player', max_length=10)),
                ('token', models.CharField(default=games.models.generate_participant_token, max_length=64, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('drinks_taken', models.PositiveIntegerField(default=0)),
                ('drinks_given', models.PositiveIntegerField(default=0)),
                ('connected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_assignments', to='games.boardcell')),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks_dealt', to='games.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks_received', to='games.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Buzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='games.boardcell')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzes', to='games.participant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='boardcell',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_cells', to='games.participant'),
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('game', 'position'), name='unique_column_position'),
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('game', 'category'), name='unique_column_category'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_participant_name_per_game'),
        ),
        migrations.AddConstraint(
            model_name='buzz',
            constraint=models.UniqueConstraint(fields=('cell', 'participant'), name='one_buzz_per_participant_per_cell'),
        ),
        migrations.AddConstraint(
            model_name='boardcell',
            constraint=models.UniqueConstraint(fields=('column', 'row'), name='unique_cell_per_column_row'),
        ),
    ]
