# Generated by Django 6.0.7 on 2026-07-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='answer_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='won_games', to='games.participant'),
        ),
    ]
