# Generated by Django 6.0.7 on 2026-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_answer_revealed_game_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='buzzer_sound',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
