# Generated by Django 6.0.7 on 2026-07-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_participant_buzzer_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcell',
            name='drinks_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='judged_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='judged_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.participant'),
        ),
    ]
