# Generated by Django 6.0.7 on 2026-07-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_boardcell_drinks_assigned_game_judged_correct_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique_participant_name_per_game',
        ),
        migrations.AddField(
            model_name='participant',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('game', 'name'), name='unique_participant_name_per_game'),
        ),
    ]
