# Generated by Django 6.0.7 on 2026-07-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_participant_unique_participant_name_per_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='buzz_sound',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sound 1'), (2, 'Sound 2'), (3, 'Sound 3'), (4, 'Sound 4')], default=1),
        ),
    ]
