# Generated by Django 6.0.7 on 2026-07-31 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_buzz_sound'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.tournament'),
        ),
        migrations.CreateModel(
            name='TournamentAdvancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.game')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancers', to='games.tournament')),
            ],
            options={
                'ordering': ('round_number', 'source_game_id', 'rank', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'name'), name='unique_tournament_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='tournamentadvancer',
            constraint=models.UniqueConstraint(fields=('tournament', 'round_number', 'source_game', 'name'), name='unique_advancer_per_round_game_name'),
        ),
    ]
