# Generated by Django 6.0.8 on 2026-08-07 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_round_number_tournament_game_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='claimed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.participant'),
        ),
        migrations.AddField(
            model_name='tournamentadvancer',
            name='source_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.participant'),
        ),
        migrations.AddField(
            model_name='tournamentadvancer',
            name='target_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.game'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('claimed_from__isnull', False)), fields=('game', 'claimed_from'), name='unique_claim_per_game_source'),
        ),
    ]
