# Generated by Django 6.0.8 on 2026-08-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_participant_claimed_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcell',
            name='is_thunder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcell',
            name='thunder_chugger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.participant'),
        ),
        migrations.AddField(
            model_name='boardcell',
            name='thunder_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcell',
            name='thunder_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardcell',
            name='thunder_wager',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='buzz_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
