# Generated by Django 6.0.7 on 2026-07-26 17:46

import django.db.models.deletion
import trivia.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('moderation_status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('moderation_note', models.TextField(blank=True, help_text='Reviewer feedback on rejection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[trivia.validators.validate_image])),
                ('owner', models.ForeignKey(blank=True, help_text='Null for official (site-provided) content.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('moderation_status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('moderation_note', models.TextField(blank=True, help_text='Reviewer feedback on rejection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('answer', models.CharField(max_length=500)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='1 (easy) to 5 (hard); drives board row/value placement.')),
                ('media_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], default='none', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/', validators=[trivia.validators.validate_image])),
                ('audio', models.FileField(blank=True, null=True, upload_to='questions/audio/', validators=[trivia.validators.validate_audio])),
                ('video', models.FileField(blank=True, null=True, upload_to='questions/video/', validators=[trivia.validators.validate_video])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trivia.category')),
                ('owner', models.ForeignKey(blank=True, help_text='Null for official (site-provided) content.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_category_name_per_owner'),
        ),
    ]
