# Generated by Django 6.0.7 on 2026-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='media_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
