# Generated by Django 6.0.8 on 2026-08-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('trivia', '0006_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='entitlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_categories', to='billing.entitlement'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
